# Site settings
title: MPR
email: mompreneurswebde@gmail.com
url: http://mpr-web.github.io/
description: "MomPreneurs GitHub Repo"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#C3A2A4'

# Footer settings
footer: Theme StartBootstrap - Jekyll Version Jerome Lachaud

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mompreneursde
  - title: facebook
    url: https://facebook.com/mompreneursde
  - title: github
    url: https://github.com/MomPreneurs

# Build settings
markdown: kramdown
permalink: pretty
